# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edfe5566a2b2aa98f0d9b72b0001ea34c1e12d13fa14626ff8e68c47b06d1bca296f91ebb207976461c79f3229355e0159a3b7747df70448ae86e429f2742c94

test:
  secret_key_base: b2c4ad4a3017a0cc3bbca7f0d05624d5bed9df66788c11d8e5c3c363d0e286cbd96f55a63a8be3f19fe278538b6ef5c8e658a8ce2a70a9616c716947721202de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
